### ISSUE TITLE
need to add workers to MIQ_WORKER_TYPES

### ISSUE THREAD

**Issue by durandom** [jameswnl/manageiq-providers-dummy_provider#8]
to create a new provider and it's workers you need to add the classes to [MIQ_WORKER_TYPES](https://github.com/ManageIQ/manageiq/blob/0b459b86307352cd4920f45833d558303d4bc5bf/lib/workers/miq_worker_types.rb#L4)

@jrafanie do you know why we just cant do like `RefreshWorker.leaf_subclasses` but need to list all explicitly?

**Comment by jrafanie** [comment]
@durandom Because we can't autoload every provider class and it's dependencies.  We need a better way to register workers instead of loading a whole provider

**Comment by durandom** [comment]
ok - @jameswnl so for now we'll have to add that to manual instructions for creating a new provider.
I dont think its worth automating that, although it should be easy (see how the Gemfile is modified by the generator)

**Comment by jameswnl** [comment]
This will be automated in https://github.com/ManageIQ/manageiq/pull/16416

**Comment by jameswnl** [comment]
PR merged.
